### PR TITLE
Migrate to .netcore

### PR DESCRIPTION
**Pull request by mahoshojoHCG**
Port the app to dotnet core.
Dotnet core is a more modern and more efficient framework than .Net Framework.

### CODE REVIEW

**Comment by Nsiso** [comment]
Hi
Thanks for helping me to port the app to .net core. It's useful for us.
But currently, I have an exam in June, so currently, I have no time to check this.
So I will hold this pull request until I finished the exam. which might need some time. (Until Dec?) After that, you might need to change something, then I will check and Merge your pull request.
I won't close this pull request yet. Please keep in touch.

**Comment by Nsiso** [comment]
Have you got an interest in taking the charge of migrating work?
If you have, I will create a new branch for this.
The master branch should stay in .net framework and took some time to transform to .net core.

**Comment by mahoshojoHCG** [comment]
I'd love to, but currently I'm preparing for my exams. I'll be available by the end of this month. Would you like to leave your personal email address or something for better communication?

**Comment by mahoshojoHCG** [comment]
If you don't want to public your personal information, you can send it to my personal email.

**Comment by Nsiso** [comment]
我刚刚看了下你profile好像都是中国人，直接中文联系吧
有qq可以加我 2081964100
实在不行要邮件也行 siso@nsiso.com

**Comment by mahoshojoHCG** [comment]
几天前尝试添加你的好友，但是没有回应

**Comment by Nsiso** [comment]
我这里正常，没收到你的验证，但是昨天我还能收到别人的验证 = =

**Pull request closed without merging**
